# .github/project.yml
name: "Complete Bookstore API Implementation"
description: "Every endpoint from the 24-page PDF documented"
columns:
  - name: "📥 Backlog"
  - name: "📋 Spec Ready"
  - name: "👨‍💻 In Development"
  - name: "🔍 In Review"
  - name: "✅ done"

groups:
  # ========================
  # AUTHENTICATION (12 endpoints)
  # ========================
  - name: "🔐 Authentication"
    tasks:
      - title: "CORE: User Auth Endpoints"
        body: |
          ✅ POST /api/user/register
          ✅ POST /api/user/login
          ✅ POST /api/user/logout
          ✅ GET /api/user/verify
          ✅ POST /api/user/verify/2fa
          ✅ POST /api/user/verify/account/{token}
          ✅ POST /api/user/change-password
          ✅ POST /api/user/forgot-password
          ✅ POST /api/user/reset-password/{token}
          ✅ POST /api/user/toggle/2fa
        labels: ["P0", "security"]

      - title: "SOCIAL: OAuth2 Endpoints"
        body: |
          ✅ GET /api/auth/google
          ✅ GET /api/auth/facebook  
          ✅ GET /api/auth/google/callback
          ✅ GET /api/auth/facebook/callback
          ✅ GET /api/auth/social/faied
        labels: ["P1", "oauth"]

  # ========================
  # BOOK SYSTEM (28 endpoints)
  # ========================
  - name: "📚 Book Management"
    tasks:
      - title: "CRUD Operations"
        body: |
          ✅ POST /api/book/create
          ✅ GET /api/book/get-all
          ✅ GET /api/book/find/{id}
          ✅ DELETE /api/book/delete/{id}
          ✅ PUT /api/book/update-book/{id}
        labels: ["P0", "core"]

      - title: "Audio Book Handling"
        body: |
          ✅ POST /api/book/upload-audio/{id}
          ✅ GET /api/book/audio/{id}
          ✅ GET /api/book/audio-for-logged-author/{id} 
          ✅ GET /api/book/audio
          ✅ DELETE /api/book/delete-audio/{id}
          ✅ GET /api/book/audio-for-who-paid/{id}
        labels: ["P1", "media"]

      - title: "Advanced Book Queries"
        body: |
          ✅ GET /api/book/between
          ✅ GET /api/book/today
          ✅ GET /api/book/last7days
          ✅ GET /api/book/by-status/{status}
          ✅ GET /api/book/most-sold
          ✅ GET /api/book/by-authors-id/{id}
          ✅ GET /api/book/approved-by-author-id/{id}
          ✅ GET /api/book/most-reviewed
          ✅ GET /api/book/top-rated
          ✅ GET /api/book/recommendations
        labels: ["P1", "search"]

  # ========================
  # ORDER SYSTEM (22 endpoints)  
  # ========================
  - name: "💰 Orders"
    tasks:
      - title: "Order Processing"
        body: |
          ✅ POST /api/order/purchase/{id}
          ✅ GET /api/order/get-all
          ✅ GET /api/order/by-id/{id}
          ✅ PUT /api/order/update-status/{id}
          ✅ DELETE /api/order/delete/{id}
          ✅ DELETE /api/order/delete-unapproved/{id}
        labels: ["P0", "commerce"]

      - title: "Order Analytics"
        body: |
          ✅ GET /api/order/logged-user
          ✅ GET /api/order/approved-logged-user
          ✅ GET /api/order/for-book/{id}
          ✅ GET /api/order/last7days-approved
          ✅ GET /api/order/approved-byuser/{id}
          ✅ GET /api/order/byuser/{id}
          ✅ GET /api/order/bystatus/{status}
          ✅ GET /api/order/between
          ✅ GET /api/order/approved-between
          ✅ GET /api/order/today
          ✅ GET /api/order/ordernumber/{orderNumber}
          ✅ GET /api/order/last7days
        labels: ["P1", "analytics"]

  # ========================
  # USER MANAGEMENT (18 endpoints)
  # ========================
  - name: "👥 User Systems"
    tasks:
      - title: "User Profiles"
        body: |
          ✅ GET /api/user/my-profile
          ✅ POST /api/manage-user/register-byreferal/{token}
          ✅ PUT /api/manage-user/update-my-account
          ✅ GET /api/manage-user/get-all-users
          ✅ GET /api/manage-user/my-referal
          ✅ DELETE /api/manage-user/delete-my-account
          ✅ GET /api/manage-user/get-user/{id}
        labels: ["P1", "profile"]

      - title: "Admin Controls"
        body: |
          ✅ GET /api/manage-user/filter-authors
          ✅ GET /api/manage-user/filter-allusers
          ✅ PUT /api/manage-user/toggle/isactive/{id}
          ✅ GET /api/manage-user/not-active-users
          ✅ GET /api/manage-user/verified-users
          ✅ PUT /api/manage-user/change-role/{id}
          ✅ GET /api/manage-user/provider/{provider}
          ✅ POST /api/manage-user/send-email/{id}
        labels: ["P2", "admin"]

  # ========================
  # FINANCIAL (14 endpoints)
  # ========================
  - name: "💳 Financial"
    tasks:
      - title: "Bank Accounts"
        body: |
          ✅ POST /api/account/create
          ✅ GET /api/account/get-all
          ✅ GET /api/account/by/{id}
          ✅ PUT /api/account/update/{id}
          ✅ DELETE /api/account/delete/{id}
        labels: ["P1", "banking"]

      - title: "Subscriptions"
        body: |
          ✅ POST /api/subscription/create
          ✅ PUT /api/subscription/update/{id}
          ✅ GET /api/subscription/get-all
          ✅ DELETE /api/subscription/delete/{id}
          ✅ GET /api/subscription/my/subscription
          ✅ GET /api/subscription/by-id/{id}
          ✅ POST /api/subscription-order/purchase
          ✅ PUT /api/subscription-order/update-status/{id}
          ✅ GET /api/subscription-order/by/{id}
        labels: ["P2", "billing"]

  # ========================
  # SOCIAL FEATURES (16 endpoints)
  # ========================
  - name: "💬 Social"
    tasks:
      - title: "Following System"
        body: |
          ✅ POST /api/following/follow
          ✅ POST /api/following/unfollow
          ✅ GET /api/following/followers/{id}
          ✅ GET /api/following/following/{id}
          ✅ GET /api/following/myfollowers
          ✅ GET /api/following/amfollowing
        labels: ["P2", "social"]

      - title: "Reviews & Comms"
        body: |
          ✅ POST /api/review/create/{id}
          ✅ PUT /api/review/update/{id}
          ✅ GET /api/review/get-all
          ✅ DELETE /api/review/delete/{id}
          ✅ GET /api/review/by-userid/{id}
          ✅ GET /api/review/by-bookid/{id}
          ✅ GET /api/review/by/{id}
          ✅ POST /api/comm/create
          ✅ PUT /api/comm/update/{id}
          ✅ DELETE /api/comm/delete/{id}
        labels: ["P1", "content"]

  # ========================
  # REPORTING (17 endpoints)
  # ========================
  - name: "📊 Analytics"
    tasks:
      - title: "Sales Reports"
        body: |
          ✅ GET /api/sales/books/reports/bybookid/{id}
          ✅ GET /api/sales/books/reports/logged-author
          ✅ GET /api/sales/books/reports/total-byauthorid/{id}
          ✅ GET /api/sales/books/reports/top-books
          ✅ GET /api/sales/books/reports/top-sellers
          ✅ GET /api/sales/books/reports/top-buyer
          ✅ GET /api/sales/books/reports/total
          ✅ GET /api/sales/books/reports/last7days
          ✅ GET /api/sales/books/reports/average
          ✅ GET /api/sales/books/reports/last-month
          ✅ GET /api/sales/books/reports/last-year
          ✅ GET /api/sales/books/reports/this-month
          ✅ GET /api/sales/books/reports/this-year
          ✅ GET /api/sales/books/reports/between
          ✅ GET /api/sold-report/between
          ✅ GET /api/sold-report/get-totals
          ✅ GET /api/sold-report/get-all
        labels: ["P1", "analytics"]

automation:
  rules:
    - name: "Start development when assigned"
      conditions:
        - assigned: true
      actions:
        - set_column: "👨‍💻 In Development"
        - add_label: "active"

    - name: "Move to review when PR created"
      conditions:
        - linked_pull_request: any  
      actions:
        - set_column: "🔍 Code Review"
        - add_label: "under-review"
